### ISSUE TITLE
Reto 3 - Comentarios

### ISSUE THREAD

**Issue by andresmgsl** [lokywolf2295/Curso-Solana#10]
Bien bro, acabo de revisar lo que enviaste del reto 3, todo está bien, felicidades, solo dos comentarios pequeños, el primero es que  para poder transferir el monto que muestras en tu modal de transferencia, tienes que multiplicar por el número de decimales que tiene el token, en este caso SILLY tiene 9, por lo que el amount correcto para transferir 1 SILLY, sería 1 * 10⁹ ... Actualmente pasas el amount directo con el valor que te viene del formulario, entonces al colocar 1 de amount, realmente estarías transfirendo 0,000000001 SILLY (la unidad mínima)... Hay muchas formas de arreglarlo, la mas sencilla es simplemente multiplicar el amount antes de hacer la llamada. Te dejo unas imágenes para intentar ilustrar un poco mejor lo que digo:

Sin multiplicar el amount, se ve así la transferencia (fíjate que dice 0 en el amount de SILLY del modal de la wallet) ->
![Screenshot from 2024-02-29 15-12-18](https://github.com/lokywolf2295/Curso-Solana/assets/6069831/d64e2b08-c89c-492f-9904-21f3c75457a2)

Multiplicando el amount por los decimales se ve así (Fíjate como ahora si se muestra 2 SILLY )->
![Screenshot from 2024-02-29 15-18-54](https://github.com/lokywolf2295/Curso-Solana/assets/6069831/5390a847-7b4e-4ccd-9480-a590851a6441)

La linea de código es aquí ->
![Screenshot from 2024-02-29 15-12-32](https://github.com/lokywolf2295/Curso-Solana/assets/6069831/e2675898-4dd4-4f75-9dc8-12de1b99fae4)

Si no logré explicarme correctamente avísame y lo vemos en mas detalle bro.

El segundo comentario es que, no pusiste las comilals correctas y al hacer la transferencia, en vez de mostrar el signature, literal se muestra es ${signature}.. te faltaría poner las otras comillas ->  `

![Screenshot from 2024-02-29 15-20-58](https://github.com/lokywolf2295/Curso-Solana/assets/6069831/5dba7e32-8fd2-4087-b68d-a0f3afffc24f)

**Comment by lokywolf2295** [comment]
Solucionado todo en el reto 3 bono, muchísimas gracias por esas correcciones.
