### ISSUE TITLE
selector incorrectamente definido

### ISSUE THREAD

**Issue by danmt** [lokywolf2295/Curso-Solana#4]
El atributo [`selector` de tu app component](https://github.com/lokywolf2295/Curso-Solana/blob/test/heavy/src/app/app.component.ts#L20) tiene un error. Fijate que le llamas `bob-root`, pero yo le llame así porque mi proyecto se llama `bob`, en tu caso, se llama `heavy`. 

Esto te causa dos problemas:

- Tu app espera que todos los selectors empiecen con "heavy" en lugar de "bob", al tenerlo con bob la app no te va a compilar bien.
- Si lograses saltarte el error al compilar no verias nada porque en en el [index.html estas mostrando el componente `heavy-root`](https://github.com/lokywolf2295/Curso-Solana/blob/test/heavy/src/app/app.component.ts#L20)  pero le llamaste `bob-root`.

La solución correcta es cambiar el [selector de `bob-root` a `heavy-root` en el app.component](https://github.com/lokywolf2295/Curso-Solana/blob/test/heavy/src/app/app.component.ts#L20). Recuerda que esto aplica a todos los componentes que hagas.

**Comment by lokywolf2295** [comment]
![image](https://github.com/lokywolf2295/Curso-Solana/assets/95238399/2f5bec1f-10da-47b9-8166-8f39d424f366)
![image](https://github.com/lokywolf2295/Curso-Solana/assets/95238399/260c02ac-a739-4a3b-8df3-72afb2a98079)

Listo problema solucionado, ya está todo conectado. a seguir con el reto
