### ISSUE TITLE
Dirección del token de SILLY Incorrecta

### ISSUE THREAD

**Issue by dayanarp** [lokywolf2295/Curso-Solana#7]
![Captura de pantalla 2024-02-18 182325](https://github.com/lokywolf2295/Curso-Solana/assets/12019129/7848c2d2-3aa9-483a-8080-93bfa90df78c)

El mint address que dejaste no corresponde a la dirección de ningún token por lo que al correr tu app no se visualiza el balance de la wallet, asumo que se te olvidó descomentar la dirección correcta de SILLY que tienes allí comentada. Tu solución esta aprobada porque al descomentar el address correcto y comentar el otro, funciona bien, sin embargo te dejo el issue para que lo corrijas cuando puedas.

**Comment by lokywolf2295** [comment]
Hola @dayanarp, mucho gusto y gracias por escribirme, la addres: 7VcnUPSoYq9bcfCUhsxdVPdKEnkw8Rkf7Qc6BMcyg4JB es la de mi billetera.

Y cuando recien empezamos el reto no me figuraban fondos por ende no funcionaba, la que está comentada, es la direccion de danmt del tutorial. y con esa si funcionaba. ahora yo cuando pongo mi direción y mi token si funciona todo.

![image](https://github.com/lokywolf2295/Curso-Solana/assets/95238399/10e0eec6-286a-476a-8fd3-fcb3f72722d4)

Si ves en la imagen, se ven mis fondos de Silly Dragons, y además a la derecha y en el centro se ven el principio y final de mi dirección. así mismo se ven que los fondos coinciden.

Igual quedo atento a tu respuesta
